---
- name: Install php-fpm and deps 
  apt: pkg={{ item }} state=present
  become: true
  with_items:
    - php5
    - php5-fpm
    - php5-sqlite
    - php-db


# - name: Disable default pool
#   become: true
#   command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
#   notify: restart php-fpm
 
# - name: Copy php-fpm configuration
#   template: src=webserver.conf dest=/etc/php-fpm.d/
#   become: true
#   notify: restart php-fpm