
---
 - name: ohmyzsh installed
   sudo: no
   shell: cp -n ~/.oh-my-zsh/templates/zshrc.zsh-template ~/.zshrc

 - name: setup dotfiles
   sudo: no
   shell: cd ~/.personalconfig/ && ansible-playbook -i hosts ansible-dotfiles.yml

