---
 - name: Ubuntu specific packages
   apt: pkg={{ item }} state=latest
   become: true
   tags: [utilapps, debian]
   with_items:
    - git
    - zsh
    - git-core
    - emacs24
    - python-pip
    - python-dev
    - ack-grep
    - build-essential
    - tmux
    - guake
    - colordiff
    - clipit
    - htop

 - name: Ubuntu specific optional packages
   apt: pkg={{ item }} state=latest
   become: true
   tags: [utilapps, debian]
   ignore_errors: yes
   with_items:
    - libffi-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - libjpeg8-dev
    - zlib1g-dev

 - name: Set zsh as default shell
   become: true
   user: name={{ ansible_ssh_user }} shell=/bin/zsh
   tags: [zsh, debian]

