---
 - name: Ubuntu specific packages
   apt:
     pkg:
     - git
     - zsh
     - git-core
     - emacs
     - python3-pip
     - python3-dev
     - ack-grep
     - build-essential
     - tmux
     - guake
     - colordiff
     - clipit
     - htop
     state: latest
   become: true
   tags: [utilapps, debian]

 - name: Ubuntu specific optional packages
   ignore_errors: yes
   apt:
     pkg: 
     - libffi-dev
     - libssl-dev
     - libxml2-dev
     - libxslt1-dev
     - libjpeg8-dev
     - zlib1g-dev
     state: latest
   become: true
   tags: [utilapps, debian]

 - name: Set zsh as default shell
   become: true
   user: name={{ansible_env.USER}} shell=/bin/zsh
   tags: [zsh, debian]

