---
 - name: FreeBSD specific packages
   pkgng:
     name:
     - git
     - zsh
     - emacs
     - py27-pip
     - ack
     - tmux
     - guake
     - yakuake
     - colordiff
     - clipit     
     state: present
   become: true
   tags: [utilapps, pcbsd]
   when: ansible_os_family == "FreeBSD"

 - name: Set zsh as default shell
   become: true
   user: name={{ ansible_ssh_user }} shell=/usr/local/bin/zsh
   tags: [zsh, pcbsd]
   when: ansible_os_family == "FreeBSD"
