---
 - include: osx.yml
   when: ansible_os_family == "Darwin"

 - include: debian.yml
   when: ansible_os_family == "Debian"

 - name: install/update ansible and other python packages
   sudo: yes
   pip: name={{ item }} state=latest
   tags: [pythonpackages,utilapps,pip]
   with_items:
    - ansible
    - requests
    - httpie
    - ipython

 - name: Check-out oh-my-zsh 
   sudo: no
   git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh update=yes
   notify: ohmyzsh installed
   tags: [zsh,zshaddon]

 - name: Install zsh-syntaxhighlight
   sudo: no
   git: repo=git://github.com/zsh-users/zsh-syntax-highlighting.git dest=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
   tags: [zsh,zshaddon]
   
 - name: Install zsh-autosuggestions
   sudo: no
   git: repo=https://github.com/tarruda/zsh-autosuggestions dest=~/.zsh-autosuggestions update=yes
   tags: [zsh,zshaddon]

 - name: Enable zsh-autusuggestion plugin
   sudo: no
   lineinfile: dest=~/.zshrc state=present create=yes insertbefore='source.*oh-my-zsh\.sh'
                  regexp='^plugins=\(.*\)' line="plugins=(git zsh-syntax-highlighting)"
   tags: [zsh,zshaddon]
   
 - name: Create temp and bin directories in home
   sudo: no
   shell: mkdir -p ~/tmp/ ~/bin/
   tags: [persconf]

 - name: Checkout bashmarks
   sudo: no
   git: repo=https://github.com/sharjeel/bashmarks.git dest=~/tmp/bashmarks update=yes
   tags: [persconf, bashmarks]

 - name: Install bashmarks
   sudo: no 
   shell: cd ~/tmp/bashmarks && make install
   tags: [persconf, bashmarks]

 - name: Checkout personalized dotfiles
   sudo: no
   git: repo=https://github.com/sharjeel/dotfiles.git dest=~/.personalconfig/ update=yes
   notify:
        setup dotfiles
   tags: [persconf]

 - name: Setup personalized dotfiles
   sudo: no
   shell: ansible-playbook ~/.personalconfig/ansible-dotfiles.yml -i ~/.personalconfig/localhost 
   tags: [persconf]

 - name: Copy over emacs batch script for installing 
   sudo: no
   template: src=emacs.script.el dest=~/tmp/emacs.script.el
   tags: [persconf, emacs]

 - name: Install emacs packages
   sudo: no
   shell: emacs --script ~/tmp/emacs.script.el | head -1
   tags: [persconf, emacs]

 - name: Clean over installation file
   sudo: no
   file: path=~/tmp/emacs.script.el state=absent
   tags: [persconf, emacs]

