---
 - include: osx.yml
   when: ansible_os_family == "Darwin"

 - include: debian.yml
   when: ansible_os_family == "Debian"

 - include: debian.yml
   when: ansible_os_family == "Linuxmint"

 - include: freebsd.yml
   when: ansible_os_family == "FreeBSD"

 - name: try ansible/pip updates
   become: true
   pip: name={{ item }} state=latest
   tags: [pip,ansible]
   ignore_errors: yes
   with_items:
     - pip
     - ansible

 - name: install/update python packages
   become: true
   pip: name={{ item }} state=latest
   tags: [pythonpackages,utilapps]
   with_items:
    - requests
    - httpie
    - pyzmq
    - zmq
    - jsonschema
    - tornado
    - virtualenv
    - virtualenvwrapper

 - name: Install IPython LTS which supports Python 2.7
   become: true
   pip: name=ipython state=present version=5.4
   tags: [pythonpackages,utilapps]

 - name: Check-out oh-my-zsh 
   become: false
   git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh update=yes
   notify: ohmyzsh copy rc
   tags: [zsh,zshaddon,ohmyzsh]

 - name: Install zsh-syntaxhighlight
   become: false
   git: repo=git://github.com/zsh-users/zsh-syntax-highlighting.git dest=~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
   tags: [zsh,zshaddon]
   
 - name: Install zsh-autosuggestions
   become: false
   git: repo=https://github.com/tarruda/zsh-autosuggestions dest=~/.zsh-autosuggestions update=yes
   tags: [zsh,zshaddon]

 - name: Enable zsh-autusuggestion plugin
   become: false
   lineinfile: dest=~/.zshrc state=present create=yes insertbefore='source.*oh-my-zsh\.sh'
                  regexp='^plugins=\(.*\)' line="plugins=(git extract zsh-syntax-highlighting)"
   tags: [zsh,zshaddon]
   
 - name: Create temp and bin directories in home
   become: false
   shell: mkdir -p ~/tmp/ ~/bin/
   tags: [persconf]

 - name: Checkout bashmarks
   become: false
   git: repo=https://github.com/sharjeel/bashmarks.git dest=~/tmp/bashmarks update=yes
   tags: [persconf, bashmarks]

 - name: Install bashmarks
   become: false 
   shell: cd ~/tmp/bashmarks && make install
   tags: [persconf, bashmarks]

 - name: Checkout personalized dotfiles
   become: false
   git: repo=https://github.com/sharjeel/dotfiles.git dest=~/.personalconfig/ update=yes
   notify:
        setup dotfiles
   tags: [persconf]

 - name: Setup personalized dotfiles
   become: false
   shell: ansible-playbook ~/.personalconfig/ansible-dotfiles.yml -i ~/.personalconfig/localhost 
   tags: [persconf]

 - name: Copy over emacs batch script for installing 
   become: false
   template: src=emacs.script.el dest=~/tmp/emacs.script.el
   tags: [persconf, emacs]

 - name: Install emacs packages
   become: false
   shell: emacs --script ~/tmp/emacs.script.el | head -1
   tags: [persconf, emacs]

 - name: Clean over installation file
   become: false
   file: path=~/tmp/emacs.script.el state=absent
   tags: [persconf, emacs]

