---
 - name: install emacs24, git, zsh, gcc, gnu-make,
   apt: pkg={{ item }} state=latest
   sudo : yes
   tags: [utilapps]
   with_items:
    - git
    - zsh
    - git-core
    - emacs24
    - python-pip
    - python-dev
    - ack-grep
    - build-essential

 - name: install ansible
   sudo: yes
   pip: name=ansible

 - name: Check-out oh-my-zsh 
   sudo: no
   git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=~/.oh-my-zsh update=yes
   notify:
        ohmyzsh installed

 - name: Set zsh as default shell
   sudo: yes
   user: name={{ ansible_ssh_user }} shell=/bin/zsh
   tags: [shell]

 - name: Create temp and bin directories in home
   sudo: no
   shell: mkdir -p ~/tmp/ ~/bin/
   tags: [persconf]

 - name: Checkout bashmarks
   sudo: no
   git: repo=https://github.com/sharjeel/bashmarks.git dest=~/tmp/bashmarks update=yes
   tags: [persconf, bashmarks]

 - name: Install bashmarks
   sudo: no 
   shell: cd ~/tmp/bashmarks && make install
   tags: [persconf, bashmarks]

 - name: Checkout personalized dotfiles
   sudo: no
   git: repo=https://github.com/sharjeel/dotfiles.git dest=~/.personalconfig/ update=yes
   notify:
        setup dotfiles
   tags: [persconf]

 - name: Setup personalized dotfiles
   sudo: no
   shell: ansible-playbook ~/.personalconfig/ansible-dotfiles.yml -i ~/.personalconfig/localhost 
   tags: [persconf]

 - name: Copy over emacs batch script for installing 
   sudo: no
   template: src=emacs.script.el dest=~/tmp/emacs.script.el
   tags: [persconf, emacs]

 - name: Install emacs packages
   sudo: no
   shell: emacs --script ~/tmp/emacs.script.el | head -1
   tags: [persconf, emacs]

 - name: Clean over installation file
   sudo: no
   file: path=~/tmp/emacs.script.el state=absent
   tags: [persconf, emacs]

