---
 - name: OSX Specific packages via homebrew
   homebrew:
     name: emacs,ack,tmux
     state: present 
   tags: [utilapps, darwin]
   when: ansible_os_family == "Darwin"

 - name: Set ZSH as default shell
   become: true
   shell: chsh -s /bin/zsh sharjeel
   tags: [zsh, darwin]
   when: ansible_os_family == "Darwin"